### PR TITLE
add typescript tests (#9)

### PR DESCRIPTION
**Pull request by zixia**

### CODE REVIEW

**Comment by munro** [comment]
Waa I pushed some code too—but I rebased on top of your branch so you can pull in my changes!

```bash
git remote add munro git@github.com:Submersible/node-python-bridge.git
git pull munro/typescript
```

**Comment by munro** [comment]
@zixia Do you know why the tests are failing?  I've had the same issue locally when playing with TypeScript.

**Comment by zixia** [comment]
@munro I have no problem in my Ubuntu 17.04 amd64 box.

```shell
$ npm t

> python-bridge@1.0.0 test /home/zixia/git/node-python-bridge
> npm run test:js && npm run test:ts


> python-bridge@1.0.0 test:js /home/zixia/git/node-python-bridge
> tap test.js

(node:12392) Warning: process.on(SIGPROF) is reserved while debugging
test.js (node:12398) Warning: process.on(SIGPROF) is reserved while debugging
test.js ............................................. 30/30
total ............................................... 30/30

  30 passing (926.316ms)

  ok

> python-bridge@1.0.0 test:ts /home/zixia/git/node-python-bridge
> ts-node test.ts

TAP version 13
    # Subtest: TypeScript
    1..1
(node:12462) Warning: process.on(SIGPROF) is reserved while debugging
    ok 1 - should be equal
ok 1 - TypeScript # time=19.427ms

1..1
# time=31.288ms
```

Will have a look into the CI tests.

**Comment by zixia** [comment]
It's a little wired.

I deleted my local directory, and re-clone from the github, the tests run fine.

```shell
$ git clone git@github.com:zixia/node-python-bridge.git
Cloning into 'node-python-bridge'...
remote: Counting objects: 97, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 97 (delta 8), reused 20 (delta 7), pack-reused 73
Receiving objects: 100% (97/97), 49.84 KiB | 0 bytes/s, done.
Resolving deltas: 100% (52/52), done.
┌ zixia@zixia-desktop:~/git [00:59:06] tty:[1] jobs:[0]
└ $ cd node-python-bridge/
┌ zixia@zixia-desktop:~/git/node-python-bridge [00:59:08] tty:[1] jobs:[0]
└ (master) $ npm i
npm notice created a lockfile as package-lock.json. You should commit this file.
added 387 packages in 14.143s
┌ zixia@zixia-desktop:~/git/node-python-bridge [00:59:24] tty:[1] jobs:[0]
└ {master} $ npm t

> python-bridge@1.0.0 test /home/zixia/git/node-python-bridge
> npm run test:js && npm run test:ts


> python-bridge@1.0.0 test:js /home/zixia/git/node-python-bridge
> tap test.js

test.js ............................................. 30/30
total ............................................... 30/30

  30 passing (934.917ms)

  ok

> python-bridge@1.0.0 test:ts /home/zixia/git/node-python-bridge
> ts-node test.ts

TAP version 13
# Subtest: TypeScript
    1..1
    ok 1 - should be equal
ok 1 - TypeScript # time=19.331ms

1..1
# time=31.801ms

┌ zixia@zixia-desktop:~/git/node-python-bridge [00:59:30] tty:[1] jobs:[0]
└ {master} $ node -v
v8.1.4
┌ zixia@zixia-desktop:~/git/node-python-bridge [01:00:46] tty:[1] jobs:[0]
└ {master} $ npm -v
5.3.0
```

BTW I'm using node v8 and npm v5. Will switch to a server to test it.

**Comment by zixia** [comment]
It seems that I had already fixed TravisCI :D

Related diff: 

```diff
- declare module "python-bridge" {
+ // declare module "python-bridge" {
```

**Comment by zixia** [comment]
There are two CI fail left:
1. https://travis-ci.org/Submersible/node-python-bridge/jobs/255386830
1. https://ci.appveyor.com/project/munro/node-python-bridge/build/1.0.58/job/c873eakmyjo377sg

**Comment by munro** [comment]
Awesome that was the fix I was looking for... removing `declare module "python-bridge" {`

I pushed some changes, it's looking good to go—but one final thing I'm thinking about changing is

```typescript
import { pythonBridge } from 'python-bridge';
const python = pythonBridge();
```

Into

```typescript
import { PythonBridge } from 'python-bridge';
const python = new PythonBridge();
```

Does that sound good to you?  It seems like it would be a lot more idiomatic.

**Comment by zixia** [comment]
Yes, TypeScript is sometimes wired: when we define a `module` then there will get a `no module` error...

I'm very happy that you think we are looking good to go. I agree that it's good to have one name `PythonBridge` than we have two: `pythonBridge` and `PythonBridge`.

I will vote for your new suggestion, because it's a more clear class, and then we will have the change to rewrite all the code to TypeScript:
```
import { PythonBridge } from 'python-bridge';
const python = new PythonBridge();
```

and I think we can use an instance method to replace "const foo = python`1 + 2`", e.g.:
```
python.eval`1 + 2`
```

**Pull request merged**
